# Generated by Django 3.2.5 on 2021-07-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laRoja', '0002_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cate'),
        ),
    ]
