# Generated by Django 3.2.5 on 2021-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laRoja', '0003_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
