# Generated by Django 3.2.5 on 2021-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laRoja', '0006_noticia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='noticias/no_imagen.jpg', upload_to='noticias'),
        ),
    ]
