# Generated by Django 3.2.5 on 2021-07-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laRoja', '0007_alter_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('comentario', models.TextField(null=True)),
            ],
        ),
    ]
